services:
  app:
    build: .
    container_name: geoapi_app
    env_file: .env
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    depends_on:
      - postgres
    command: ["rails", "server", "-b", "0.0.0.0"]
    networks:
      - geoapi_network

  postgres:
    image: postgres:16
    container_name: geoapi_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
     - geoapi_network

volumes:
  postgres_data:
networks:
  geoapi_network:
    driver: bridge
